#!/usr/bin/env python3
# Copyright 2026 Rover A1 contributors
# Licensed under the Apache License, Version 2.0.

from rover_indoor_nav_manager.presentation.main import main

if __name__ == "__main__":
    main()
